jenkins:
  systemMessage: "Jenkins Instance"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "12345"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated" 

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github_token
              username: ${secrets.USER_GITHUB}
              password: ${secrets.PASSWORD_GITHUB}
              description: "GitHub token for Jenkins"
          
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub
              username: ${secrets.USER_DOCKER}
              password: ${secrets.DOCKER_ACCESS_TOKEN}
              description: "DockerHub token for Jenkins"

jobs:
  - file: /var/lib/jenkins/multibranch-pipeline.groovy

unclassified:
  location:
    url: https://jenkins.talentofpainting.info