name: Build-AMI-Packer

on:
  push:
    branches: [ main ]

jobs:
  ami-build:
    name: Build AMI Packer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.x'

      - name: Jenkins Configuration as Code artifacts
        run: |
          cd jenkins && cp jcasc.yaml ../ && cd ..
          cd scripts  && cp *.groovy ../ && cd ..
          tar -czvf configs.tgz jcasc.yaml *.groovy
          rm -rf jcasc.yaml *.groovy

      - name: Packer init
        run: packer init ./packer/build_ami.pkr.hcl

      - name: Packer build
        run: packer build ./packer/build_ami.pkr.hcl
