name: Validate-Packer
on:
  pull_request:
jobs:
  packer_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.x'

      - name: Set environment variables
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "SSH_USERNAME=${{ secrets.SSH_USERNAME }}" >> $GITHUB_ENV
          echo "SOURCE_AMI=${{ secrets.SOURCE_AMI }}" >> $GITHUB_ENV
          echo "AWS_ROOT_ACCOUNT_ID=${{ secrets.AWS_ROOT_ACCOUNT_ID }}" >> $GITHUB_ENV
          # echo "VPC_ID=${{ secrets.VPC_ID }}" >> $GITHUB_ENV
      
      - name: Run Packer init
        run: packer init ./packer/build_ami.pkr.hcl

      - name: Run packer fmt
        run: packer fmt ./packer/build_ami.pkr.hcl

      - name: Check for changes
        id: git-diff
        run: |
          git diff --exit-code || {
            echo "Packer template has been modified during 'packer fmt'. Please make sure your Packer template is properly formatted.";

            exit 1;
          }

      - name: Run packer validate
        run: packer validate ./packer/build_ami.pkr.hcl

      - name: Check validation status
        id: validate-status
        run: |
          if [[ $(packer validate ./packer/build_ami.pkr.hcl) == *"The configuration is valid."* ]]; then
            echo "Packer template validation succeeded."
          else
            echo "Packer template validation failed. Please fix any issues before merging."
            exit 1
          fi

      - name: Final checks
        if: ${{ steps.validate-status.outcome == 'success' }}
        run: echo "All checks passed."